package com.example.students

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
class StudentsApplication

fun main(args: Array<String>) {
	runApplication<StudentsApplication>(*args)
}
